import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "./assets/product-1.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Fire run running shoes for men",
    originalPrice: 2000,
    price: 1500,
    discount: 44,
    ratings: 4.7,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-2.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Hustle V2 Running Shoes For Men  ",
    originalPrice: 3000,
    price: 2300,
    discount: 40,
    ratings: 4.1,
    inStock: false,
    fastDelivery: true,
  },
  {
    _id: uuid(),
    img: "./assets/product-3.jpg",
    productBrand: "Puma",
    categoryName: "Women",
    productDetail: "Supertec Running Shoes For Men",
    originalPrice: 6900,
    price: 5000,
    discount: 20,
    ratings: 4.9,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-4.jpg",
    productBrand: "Puma",
    categoryName: "Women",
    productDetail: "Ferrari X-Ray Speed Running Shoes For Men",
    originalPrice: 3500,
    price: 1700,
    discount: 30,
    ratings: 3.9,
    inStock: true,
    fastDelivery: true,
  },
  {
    _id: uuid(),
    img: "./assets/product-5.jpg",
    productBrand: "Puma",
    categoryName: "Women",
    productDetail: "Troy MU Running Shoes For Men (Grey)",
    originalPrice: 4000,
    price: 3300,
    discount: 20,
    ratings: 3.2,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-5.jpg",
    productBrand: "Adidas",
    categoryName: "Women",
    productDetail: "Runesy M Running Shoes For Men  (Grey) ",
    originalPrice: 1000,
    price: 599,
    discount: 20,
    ratings: 2.0,
    inStock: false,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-6.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Pictoris M Running Shoes For Men  (Black) ",
    originalPrice: 2000,
    price: 1700,
    discount: 40,
    ratings: 3.0,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-8.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Adifloss M Running Shoes For Men  (Blue) ",
    originalPrice: 5000,
    price: 2500,
    discount: 50,
    ratings: 2.9,
    inStock: false,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-9.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Quickflow M Running Shoes For Men  (Blue)",
    originalPrice: 9000,
    price: 8000,
    discount: 10,
    ratings: 4.9,
    inStock: false,
    fastDelivery: true,
  },
  {
    _id: uuid(),
    img: "./assets/product-10.jpg",
    productBrand: "Nike",
    categoryName: "Men",
    productDetail: "Revolution 5 Running Shoes For Men  (Black) ",
    originalPrice: 2700,
    price: 2200,
    discount: 20,
    ratings: 2.8,
    inStock: false,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-11.jpg",
    productBrand: "Nike",
    categoryName: "Men",
    productDetail: "Revolution 6 Next Nature Road s Running Shoes For Men  ",
    originalPrice: 9000,
    price: 8400,
    discount: 10,
    ratings: 4.9,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-12.jpg",
    productBrand: "Nike",
    categoryName: "Men",
    productDetail: "Downshifter 11 Road s Running Shoes For Men ",
    originalPrice: 3000,
    price: 2000,
    discount: 30,
    ratings: 3.5,
    inStock: true,
    fastDelivery: true,
  },
  {
    _id: uuid(),
    img: "./assets/product-13.jpg",
    productBrand: "Nike",
    categoryName: "Men",
    productDetail: "Revolution 4 Running Shoes For Men  (Black)",
    originalPrice: 7000,
    price: 5999,
    discount: 20,
    ratings: 3.9,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-14.jpg",
    productBrand: "Nike",
    categoryName: "Men",
    productDetail: "Revolution 6 Next Nature Road Running Shoes",
    originalPrice: 5000,
    price: 3000,
    discount: 50,
    ratings: 3.1,
    inStock: false,
    fastDelivery: true,
  },
  {
    _id: uuid(),
    img: "./assets/product-15.jpg",
    productBrand: "Reebok",
    categoryName: "Men",
    productDetail: "Downshifter 11 Road s Running Shoes For Men ",
    originalPrice: 10000,
    price: 9000,
    discount: 30,
    ratings: 3.5,
    inStock: true,
    fastDelivery: true,
  },
  {
    _id: uuid(),
    img: "./assets/product-1.jpg",
    productBrand: "Reebok",
    categoryName: "Men",
    productDetail: "Revolution 4 Running Shoes For Men  (Black)",
    originalPrice: 10000,
    price: 8999,
    discount: 20,
    ratings: 3.9,
    inStock: true,
    fastDelivery: false,
  },
  {
    _id: uuid(),
    img: "./assets/product-2.jpg",
    productBrand: "Hrx",
    categoryName: "Men",
    productDetail: "Revolution 6 Next Nature Road Running Shoes",
    originalPrice: 5000,
    price: 10000,
    discount: 50,
    ratings: 3.1,
    inStock: false,
    fastDelivery: true,
  },
];
