import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "./assets/m1.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Fire run running shoes for men",
    originalPrice: 4000,
    price: 3000,
    discount: 20,
    ratings: 4.7,
    inStock: true,
    fastDelivery: false,
    productCount: 2,
  },
  {
    _id: uuid(),
    img: "./assets/m2.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Hustle V2 Running Shoes For Men  ",
    originalPrice: 5000,
    price: 4000,
    discount: 10,
    ratings: 4.1,
    inStock: false,
    fastDelivery: true,
    productCount: 3,
  },
  {
    _id: uuid(),
    img: "./assets/m3.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Supertec Running Shoes For Men",
    originalPrice: 6900,
    price: 5000,
    discount: 20,
    ratings: 4.9,
    inStock: true,
    fastDelivery: false,
    productCount: 4,
  },
  {
    _id: uuid(),
    img: "./assets/m4.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Ferrari X-Ray Speed Running Shoes For Men",
    originalPrice: 3500,
    price: 2700,
    discount: 30,
    ratings: 3.9,
    inStock: true,
    fastDelivery: true,
    productCount: 7,
  },
  {
    _id: uuid(),
    img: "./assets/m5.jpg",
    productBrand: "Puma",
    categoryName: "Men",
    productDetail: "Troy MU Running Shoes For Men (Grey)",
    originalPrice: 4000,
    price: 3300,
    discount: 20,
    ratings: 3.2,
    inStock: true,
    fastDelivery: false,
    productCount: 7,
  },
  {
    _id: uuid(),
    img: "./assets/m6.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Runesy M Running Shoes For Men  (Grey) ",
    originalPrice: 1000,
    price: 599,
    discount: 20,
    ratings: 2.0,
    inStock: false,
    fastDelivery: false,
    productCount: 8,
  },
  {
    _id: uuid(),
    img: "./assets/m7.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Pictoris M Running Shoes For Men  (Black) ",
    originalPrice: 2000,
    price: 1800,
    discount: 40,
    ratings: 3.0,
    inStock: true,
    fastDelivery: false,
    productCount: 2,
  },
  {
    _id: uuid(),
    img: "./assets/m8.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Adifloss M Running Shoes For Men  (Blue) ",
    originalPrice: 5000,
    price: 4500,
    discount: 10,
    ratings: 2.9,
    inStock: false,
    fastDelivery: false,
    productCount: 4,
  },
  {
    _id: uuid(),
    img: "./assets/m9.jpg",
    productBrand: "Adidas",
    categoryName: "Men",
    productDetail: "Quickflow M Running Shoes For Men  (Blue)",
    originalPrice: 9000,
    price: 8000,
    discount: 10,
    ratings: 4.9,
    inStock: false,
    fastDelivery: true,
    productCount: 5,
  },
  {
    _id: uuid(),
    img: "./assets/m10.jpg",
    productBrand: "Nike",
    categoryName: "Men",
    productDetail: "Revolution 5 Running Shoes For Men  (Black) ",
    originalPrice: 10000,
    price: 9000,
    discount: 20,
    ratings: 2.8,
    inStock: false,
    fastDelivery: false,
    productCount: 1,
  },
  {
    _id: uuid(),
    img: "./assets/w1.jpg",
    productBrand: "Nike",
    categoryName: "Women",
    productDetail: "Revolution 6 Next Nature Road s Running Shoes For Men  ",
    originalPrice: 9000,
    price: 8400,
    discount: 10,
    ratings: 4.9,
    inStock: true,
    fastDelivery: false,
    productCount: 3,
  },
  {
    _id: uuid(),
    img: "./assets/w2.jpg",
    productBrand: "Nike",
    categoryName: "Women",
    productDetail: "Downshifter 11 Road s Running Shoes For Men ",
    originalPrice: 3000,
    price: 2000,
    discount: 30,
    ratings: 3.5,
    inStock: true,
    fastDelivery: true,
    productCount: 6,
  },
  {
    _id: uuid(),
    img: "./assets/w3.jpg",
    productBrand: "Nike",
    categoryName: "Women",
    productDetail: "Revolution 4 Running Shoes For Men  (Black)",
    originalPrice: 7000,
    price: 6000,
    discount: 20,
    ratings: 3.9,
    inStock: true,
    fastDelivery: false,
    productCount: 9,
  },
  {
    _id: uuid(),
    img: "./assets/w4.jpg",
    productBrand: "Nike",
    categoryName: "Women",
    productDetail: "Revolution 6 Next Nature Road Running Shoes",
    originalPrice: 5000,
    price: 4000,
    discount: 30,
    ratings: 3.1,
    inStock: false,
    fastDelivery: true,
    productCount: 2,
  },
  {
    _id: uuid(),
    img: "./assets/w5.jpg",
    productBrand: "Reebok",
    categoryName: "Women",
    productDetail: "Downshifter 11 Road s Running Shoes For Men ",
    originalPrice: 10000,
    price: 9000,
    discount: 20,
    ratings: 3.5,
    inStock: true,
    fastDelivery: true,
    productCount: 1,
  },
  {
    _id: uuid(),
    img: "./assets/w6.jpg",
    productBrand: "Reebok",
    categoryName: "Women",
    productDetail: "Revolution 4 Running Shoes For Men  (Black)",
    originalPrice: 10000,
    price: 9000,
    discount: 20,
    ratings: 3.9,
    inStock: true,
    fastDelivery: false,
    productCount: 8,
  },
  {
    _id: uuid(),
    img: "./assets/w7.jpg",
    productBrand: "Hrx",
    categoryName: "Women",
    productDetail: "Revolution 6 Next Nature Road Running Shoes",
    originalPrice: 11000,
    price: 10000,
    discount: 50,
    ratings: 3.1,
    inStock: false,
    fastDelivery: true,
    productCount: 4,
  },
  {
    _id: uuid(),
    img: "./assets/w8.jpg",
    productBrand: "Reebok",
    categoryName: "Women",
    productDetail: "Downshifter 11 Road s Running Shoes For Men ",
    originalPrice: 10000,
    price: 9000,
    discount: 20,
    ratings: 3.5,
    inStock: true,
    fastDelivery: true,
    productCount: 1,
  },
  {
    _id: uuid(),
    img: "./assets/w9.jpg",
    productBrand: "Reebok",
    categoryName: "Women",
    productDetail: "Revolution 4 Running Shoes For Men  (Black)",
    originalPrice: 10000,
    price: 9000,
    discount: 20,
    ratings: 3.9,
    inStock: true,
    fastDelivery: false,
    productCount: 8,
  },
  {
    _id: uuid(),
    img: "./assets/w10.jpg",
    productBrand: "Hrx",
    categoryName: "Women",
    productDetail: "Revolution 6 Next Nature Road Running Shoes",
    originalPrice: 11000,
    price: 10000,
    discount: 50,
    ratings: 3.1,
    inStock: false,
    fastDelivery: true,
    productCount: 4,
  },
];
